### PR TITLE
New dir structure + button linked to my site

### PR DESCRIPTION
**Pull request by shinysocks**
is this what you wanted?

### CODE REVIEW

**Review by jagernet-ops — CHANGES_REQUESTED** [review]
There should be two directories accessible from the root. One `src` directory contains all html files, and a second directory named assets containing sub-directories for each file type. 
--------
ROOT:
--------
src/
assets/
README.md
--------
SRC:
--------
index.html
java.html
bedrock.html
--------
ASSETS:
--------
css/
images/
--------

Place the files into their respective directories.  The favicon is the only file which does not follow this convention to a t. You can place it either in the images directory or inside of the root of the directory structure.

**Comment by shinysocks** [comment]
this makes sense but do you have a source for this information? Is this a common structure for websites? From the mozilla docs, I think having src and assets folders are unnessesary: [mozilla](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files#what_structure_should_your_website_have)

**Comment by jagernet-ops** [comment]
I subscribe to the formatting of a web app constructor. When you use a tool like create-react-app or NextJS it creates this form of directory formatting. Mozilla's documentation does not list this as a requirement because it simply is not one. While our projects are small and static right now I want them to align to this formatting so we are accustomed to where to find certain files and how to prevent the end user from being capable of enumerating our web app's contents. This is the reasoning behind my "liberal" use of ../​ in html elements.
________________________________

**Comment by shinysocks** [comment]
for convienience in terms of hosting, the format in the commits above works well. Can we use this? having a src and assets folder doesn't make sense. If you disagree let's chat about this in person

**Review by jagernet-ops — APPROVED** [review]

**Pull request merged**
